artifactId=pub.lib.Java_util.common
contentsModel=self-contained
description=Basic support for Java development
documentation.generatedAt=2026-09-21T10:47:39Z
documentation.sourceCommit=9a2268f3aa46ab3894a48cda54970116ee30d0d9
documentation.sourceRef=main
gradleProjectPath=:util:common
groupId=eu.algites.lib.common
java.maven.artifactId=pub.lib.Java_util.common
java.maven.groupId=eu.algites.lib.common
java.maven.version=1.0-SNAPSHOT
localArtifactId=util.common
name=Common Java Utilities
path=util/common
structureKind=artifact
technologyKinds=java
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
