artifactId=pub.lib.Java_util.documentation
contentsModel=self-contained
description=Utilities for creation of the AST (abstract syntax tree) of any documentation structure.
documentation.generatedAt=2026-09-22T13:04:53Z
documentation.sourceCommit=9a2268f3aa46ab3894a48cda54970116ee30d0d9
documentation.sourceRef=main
gradleProjectPath=:util:documentation
groupId=eu.algites.lib.common
java.maven.artifactId=pub.lib.Java_util.documentation
java.maven.groupId=eu.algites.lib.common
java.maven.version=1.0-SNAPSHOT
localArtifactId=util.documentation
name=Utilities for documentation AST building
path=util/documentation
structureKind=artifact
technologyKinds=java
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
