artifactId=pub.lib.Java_util.common
contentsModel=self-contained
description=Basic support for Java development
gradleProjectPath=:util:common
groupId=eu.algites.lib.common
kind=artifact
localArtifactId=util.common
name=Common Java Utilities
path=util/common
type=java
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
