artifactId=pub.lib.Java_util.version
contentsModel=self-contained
description=Utilities for versioning and version management
documentation.generatedAt=2026-09-21T10:47:39Z
documentation.sourceCommit=9a2268f3aa46ab3894a48cda54970116ee30d0d9
documentation.sourceRef=main
gradleProjectPath=:util:version
groupId=eu.algites.lib.common
java.maven.artifactId=pub.lib.Java_util.version
java.maven.groupId=eu.algites.lib.common
java.maven.version=1.0-SNAPSHOT
localArtifactId=util.version
name=Utilities for version management
path=util/version
structureKind=artifact
technologyKinds=java
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
