artifactId=pub.lib.General_common
contentsModel=self-contained
description=General-purpose support Open source utilities shared across Algites artifacts and repositories.
documentation.generatedAt=2026-09-26T17:48:37Z
documentation.sourceCommit=1b2edb9ce90ba2d1cbee8e21a10bc048952cb705
documentation.sourceRef=main
gradleProjectPath=:common
groupId=eu.algites.lib.common
java.maven.artifactId=pub.lib.General_common
java.maven.groupId=eu.algites.lib.common
java.maven.version=1.0-SNAPSHOT
localArtifactId=common
name=General purpose modules and utilities
path=common
structureKind=artifact
technologyKinds=java
version.lane=1
version.qualifierKind=snapshot
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
